// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"
import "regexp"

type Extra struct {
	// N corresponds to the JSON schema field "n".
	N float64 `json:"n" yaml:"n" mapstructure:"n"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Extra) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["n"]; raw != nil && !ok {
		return fmt.Errorf("field n in Extra: required")
	}
	type Plain Extra
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Extra(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Extra) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["n"]; raw != nil && !ok {
		return fmt.Errorf("field n in Extra: required")
	}
	type Plain Extra
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Extra(plain)
	return nil
}

type UnevaluatedPropertiesRef struct {
	// Known corresponds to the JSON schema field "known".
	Known string `json:"known" yaml:"known" mapstructure:"known"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UnevaluatedPropertiesRef) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["known"]; raw != nil && !ok {
		return fmt.Errorf("field known in UnevaluatedPropertiesRef: required")
	}
	{
		allowed := map[string]struct{}{
			"known": {},
		}
		for k := range raw {
			if _, ok := allowed[k]; ok {
				continue
			}
			matched := false
			patterns := make([]*regexp.Regexp, 0, 1)
			if re, err := regexp.Compile("^p_"); err == nil {
				patterns = append(patterns, re)
			}
			for _, re := range patterns {
				if re.MatchString(k) {
					matched = true
					break
				}
			}
			if matched {
				continue
			}
			b, _ := json.Marshal(raw[k])
			var v Extra
			if err := json.Unmarshal(b, &v); err != nil {
				return fmt.Errorf("field %s in UnevaluatedPropertiesRef: invalid", k)
			}
		}
	}
	type Plain UnevaluatedPropertiesRef
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UnevaluatedPropertiesRef(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *UnevaluatedPropertiesRef) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["known"]; raw != nil && !ok {
		return fmt.Errorf("field known in UnevaluatedPropertiesRef: required")
	}
	{
		allowed := map[string]struct{}{
			"known": {},
		}
		for k := range raw {
			if _, ok := allowed[k]; ok {
				continue
			}
			matched := false
			patterns := make([]*regexp.Regexp, 0, 1)
			if re, err := regexp.Compile("^p_"); err == nil {
				patterns = append(patterns, re)
			}
			for _, re := range patterns {
				if re.MatchString(k) {
					matched = true
					break
				}
			}
			if matched {
				continue
			}
			b, _ := json.Marshal(raw[k])
			var v Extra
			if err := json.Unmarshal(b, &v); err != nil {
				return fmt.Errorf("field %s in UnevaluatedPropertiesRef: invalid", k)
			}
		}
	}
	type Plain UnevaluatedPropertiesRef
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = UnevaluatedPropertiesRef(plain)
	return nil
}
